micronaut:
  application:
    name: keyManagerRest1

grpc:
  channels:
    pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false